//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiCocina_WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMENTARIO
    {
        public int IdComentario { get; set; }
        public string Comentario1 { get; set; }
        public Nullable<System.DateTime> FechaComentario { get; set; }
        public Nullable<int> IdUsuario { get; set; }
        public Nullable<int> IdRecetas { get; set; }
    
        public virtual RECETA RECETA { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
