//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiCocina_WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RECETA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RECETA()
        {
            this.CLASIFICACIONs = new HashSet<CLASIFICACION>();
            this.COMENTARIOs = new HashSet<COMENTARIO>();
            this.FAVORITOS = new HashSet<FAVORITO>();
        }
    
        public int IdRecetas { get; set; }
        public string TituloReceta { get; set; }
        public string DescripcionReceta { get; set; }
        public string IngredientesReceta { get; set; }
        public byte[] ImagenRecetas { get; set; }
        public string DificultadRecetas { get; set; }
        public string PorcionRecetas { get; set; }
        public Nullable<int> IdUsuario { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CLASIFICACION> CLASIFICACIONs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COMENTARIO> COMENTARIOs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FAVORITO> FAVORITOS { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
